notARepository: "skip" # one of: 'prompt' | 'create' | 'skip'
gui:
  showIcons: true
  scrollHeight: 2
  scrollPastBottom: true
  mouseEvents: true
  skipUnstageLineWarning: false
  skipStashWarning: true
  sidePanelWidth: 0.3333
  expandFocusedSidePanel: false
  mainPanelSplitMode: flexible
  theme:
    lightTheme: false
    activeBorderColor:
      - "#89ddff"
      - bold
    inactiveBorderColor:
      - "#565f89"
    optionsTextColor:
      - "#3d59a1"
    selectedLineBgColor:
      - "#292e42"
      - bold
    selectedRangeBgColor:
      - "#89ddff"
  commitLength:
    show: true
  skipNoStagedFilesWarning: false
os:
  openCommand: session_nvim {{filename}}
git:
  overrideGpg: true
  paging:
    colorArg: always
    pager: delta --dark --paging=never
keybinding:
  universal:
    quit-alt1: "<esc>"
customCommands:
  - key: "R"
    command: "gh repo view --web"
    description: "view repo on github"
    context: "global"
    loadingText: "opening github..."
    subprocess: false
  - key: "C"
    command: "commit"
    description: "commit with gum"
    context: "files"
    loadingText: "opening gum commit tool"
    subprocess: true
