# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
notARepository: "skip" # one of: 'prompt' | 'create' | 'skip'
promptToReturnFromSubprocess: false
gui:
  nerdFontsVersion: "3"
  showIcons: true
  showFileTree: true
  scrollHeight: 10
  scrollPastBottom: true
  mouseEvents: true
  skipDiscardChangeWarning: false
  skipStashWarning: true
  sidePanelWidth: 0.3333
  expandFocusedSidePanel: false
  mainPanelSplitMode: flexible
  theme:
    activeBorderColor:
      - "#89ddff"
      - bold
    inactiveBorderColor:
      - "#565f89"
    optionsTextColor:
      - "#3d59a1"
    selectedLineBgColor:
      - "#292e42"
      - bold
    selectedRangeBgColor:
      - "#89ddff"
  commitLength:
    show: true
  skipNoStagedFilesWarning: false
os:
  openCommand: session_nvim {{filename}}
git:
  log:
    showGraph: always
  branchLogCmd: "git log --graph --abbrev-commit --decorate --format=format:'%C(bold white)%s%C(reset) %C(dim white)- %ar %C(white)%d%C(reset)' master..{{branchName}} --"
  overrideGpg: true
  paging:
    colorArg: always
    pager: delta --dark --paging=never
customCommands:
  - key: "R"
    command: "gh repo view --web"
    description: "view repo on github"
    context: "global"
    loadingText: "opening github..."
    subprocess: false
  - key: "o"
    command: "gh pr view --web"
    description: "view PR on github"
    context: "global"
    loadingText: "opening github..."
    subprocess: false
  - key: "o"
    command: "gh pr view --web"
    description: "view PR on github"
    context: "localBranches"
    loadingText: "opening github..."
    subprocess: false
  - key: "O"
    command: "gh pr create -f --draft --head {{.SelectedLocalBranch.Name}}"
    description: "create PR on GitHub"
    context: "localBranches"
    subprocess: true
  - key: "C"
    command: "commit"
    description: "commit with gum"
    context: "files"
    loadingText: "opening gum commit tool"
    subprocess: true
