# yaml-language-server: $schema=https://json.schemastore.org/lazydocker.json
gui:
  scrollHeight: 10
  theme:
    activeBorderColor:
      - "#89ddff"
      - bold
    inactiveBorderColor:
      - "#565f89"
    optionsTextColor:
      - "#3d59a1"
    selectedLineBgColor:
      - "#292e42"
      - bold
    selectedRangeBgColor:
      - "#89ddff"
  expandFocusedSidePanel: true
commandTemplates:
  dockerCompose: docker compose
customCommands:
  containers:
    - name: fancy logs
      attach: true
      command: "{{ .DockerCompose }} logs {{ .Service.Name }} --follow | tl"
