prSections:
  - title: My Pull Requests
    filters: is:open author:@me
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: DevEnv
    filters: "is:open draft:false org:wix-private author:Galcarmi author:nemni8 author:seanoch author:haimre"
  - title: Commented
    filters: commenter:@me
  - title: "@wix"
    filters: "-author:@me -author:app/wix-loki-bot \
      repo:wix-private/wix-code-devex \
      repo:wix-private/wix-code-client \
      repo:wix-incubator/corvid-types"
  - title: gh-dash
    filters: "is:open repo:dlvhdr/gh-dash"
  - title: Closed
    filters: is:closed author:@me
  - title: WCTB
    filters: "is:pr repo:wix-private/wix-code-types-builder"
  - title: Subscribed
    filters: "\
      repo:nvim-telescope/telescope.nvim \
      repo:ldelossa/gh.nvim \
      repo:neovim/neovim \
      repo:withgraphite/graphite-cli \
      repo:cli/cli"
  - title: LSP
    filters: "-author:app/dependabot -author:app/github-action \
      repo:TypeFox/monaco-languageclient \
      repo:typescript-language-server/typescript-language-server \
      repo:CodinGame/monaco-vscode-api"
issuesSections:
  - title: Creator
    filters: author:@me
  - title: Commented
    filters: is:open commenter:@me
  - title: gh-dash
    filters: is:open repo:dlvhdr/gh-dash
  - title: Assigned
    filters: is:open assignee:@me

pager:
  diff: delta
defaults:
  layout:
    prs:
      repoName:
        grow: true,
        width: 10
        hidden: false

  preview:
    open: true
    width: 55
  prsLimit: 20
  issuesLimit: 20
repoPaths:
  wix-private/wix-code-devex: ~/code/wix/wix-code-devex-mono
  CodinGame/monaco-vscode-api: ~/code/playground/monaco-vscode-api

keybindings:
  prs:
    # - key: c
    #   command: >
    #     tmux new-window -c {{.RepoPath}} '
    #       gh pr checkout {{.PrNumber}} &&
    #       nvim -c ":DiffviewOpen master...{{.HeadRefName}}"
    #     '
    - key: v
      command: cd {{.RepoPath}} && code . # && gh pr checkout {{.PrNumber}}
theme:
  colors:
    text:
      primary: "#E2E1ED"
      secondary: "#666CA6"
      inverted: "#242347"
      faint: "#797d9c"
      warning: "#F23D5C"
      success: "#3DF294"
    background:
      selected: "#39386b"
    border:
      primary: "#383B5B"
      secondary: "#39386B"
      faint: "#2B2B40"
