prSections:
  - title: My Pull Requests
    filters: is:open author:@me
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: "DevEnv"
    filters: "is:open draft:false org:wix-private author:Galcarmi author:nemni8 author:seanoch author:haimre"
  - title: Commented
    filters: commenter:@me
  - title: "@wix"
    filters: "-author:@me -author:app/wix-loki-bot \
      repo:wix-private/wix-code-devex \
      repo:wix-private/wix-code-client \
      repo:wix-incubator/corvid-types"
  - title: gh-dash
    filters: "is:open repo:dlvhdr/gh-dash"
  - title: Closed
    filters: is:closed author:@me
issuesSections:
  - title: Creator
    filters: is:open author:@me
  - title: Commented
    filters: is:open commenter:@me
  - title: gh-dash
    filters: is:open repo:dlvhdr/gh-dash
  - title: Assigned
    filters: is:open assignee:@me
defaults:
  preview:
    open: true
    width: 55
  prsLimit: 20
  issuesLimit: 20
repoPaths:
  wix-private/wix-code-devex: ~/code/wix/devex-code-review
keybindings:
  prs:
    - key: c
      command: >
        tmux new-window -c {{.RepoPath}} '
          gh pr checkout {{.PrNumber}} &&
          nvim -c ":DiffviewOpen master...{{.HeadRefName}}"
        '
    - key: v
      command: >
        cd {{.RepoPath}} &&
        code . &&
        gh pr checkout {{.PrNumber}}
