prSections:
  - title: My Pull Requests
    filters: is:open author:@me
    layout:
      author:
        hidden: true
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: Involved
    filters: is:open involves:@me -author:@me

issuesSections:
  - title: My Issues
    filters: is:open author:@me
    layout:
      creator:
        hidden: true
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me

defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 5
      repo:
        width: 15
    issues:
      updatedAt:
        width: 5
      repo:
        width: 20
      assignees:
        hidden: true
keybindings:
  prs: []
repoPaths: {}
pager:
  diff: ""
